/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminDebugInfo {
  'totalEmployees' : bigint,
  'callerIsRegistered' : boolean,
  'callerRole' : string,
  'callerEmployeeInfo' : [] | [Employee],
  'callerIsAdmin' : boolean,
  'callerPrincipal' : string,
  'allAdminPrincipals' : Array<string>,
}
export interface AttendanceRecord {
  'checkInTime' : Time,
  'checkOutTime' : [] | [Time],
  'location' : Location,
}
export interface Employee {
  'principal' : Principal,
  'name' : string,
  'email' : string,
  'isAdmin' : boolean,
}
export interface Location { 'latitude' : number, 'longitude' : number }
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIn' : ActorMethod<[number, number], undefined>,
  'checkOut' : ActorMethod<[], undefined>,
  'getAdminDebugInfo' : ActorMethod<[], AdminDebugInfo>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMonthlyReport' : ActorMethod<
    [Principal, bigint, bigint],
    Array<AttendanceRecord>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAdmin' : ActorMethod<[string, string], undefined>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerEmployee' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];